my_string = input('введиет произвольный текст: ')
print('количество символов введённого текста -', len(my_string))
print('cтрока в верхнем регистре -', my_string.upper())
print('строка в нижнем регистре -', my_string.lower())
print('без пробелов -', my_string.replace(' ',''))
print('первый символ строки - ', my_string[0])
print('последний символ строки - ', my_string[-1])
